
# top-level NGINX proxy
nginx:
  image: nginx
  mem_limit: 512m
  ports:
    - 8080:80
  links:
    - hni-api
    - hni-db_master
  privileged: true
  volumes:
    - ./nginx/log:/var/log/nginx
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ../hni-ui/dist:/home/docker/workplace/dist



# node service to serve the data
hni-api:
  image: antouank/hni-api
  mem_limit: 512m
  restart: always
  links:
    - hni-db_master
  environment:
    NODE_ENV: 'production'
    HNI_DB_HOST:  'hni-db_master'
    HNI_DB_PORT:  '28015'
    HNI_DB_NAME:  'hn'

# node service to hook the HN feed to the DB
hni-feed:
  image: antouank/hni-feed
  mem_limit: 1024m
  links:
    - hni-db_master
  environment:
    NODE_ENV: 'production'
    HNI_DB_HOST:  'hni-db_master'
    HNI_DB_PORT:  '28015'
    HNI_DB_NAME:  'hn'


# rethinkdb  Master
hni-db_master:
  image: rethinkdb
  command: rethinkdb --bind all
  mem_limit: 4096m
  volumes:
    - ./hni-db/_db/hni-db_master:/data


